### ISSUE TITLE
Extracting passwords of the datasets?

### ISSUE THREAD

**Issue by ligaoyi101** [ihciah/deep-fashion-retrieval#3]
感谢您的分享！ 我目前也在学校里学习这方面的知识，但通过DeepFashion官方百度云链接下载的数据集需要解压密码....我发送邮件询问原作者，可能他们太忙了两个月过去了也没等到他的回复。所以，可否请您告知一下我解压密码呢？我绝对不会违背原作者意愿私自泄露，仅仅是自己学习之用。以防公开您可以单独发送至我的邮箱ligaoyi0605@126.com 期待您的回复谢谢！
----------------------------------------------------------------
刚提问完几个小时我就收到了回复，现在已经获取到解压密码了哈哈，不好意思打扰您啦

**Comment by zhuzhu18** [comment]
您好，能私发我一份解压密码吗，zhuzhu18@aliyun.com，感激不尽

**Comment by Daniellli** [comment]
您好，能私发我一份解压密码吗，[xushaocong@stu.xmu.edu.cn](xushaocong@stu.xmu.edu.cn)，感激不尽~

**Comment by fushi219** [comment]
你好，请问还能发解压密码吗？xiangyuxu@whu.edu.cn，谢谢！

**Comment by typhoon1104** [comment]
你好，请问还能发解压密码吗？typhoonxiyu@gmail.com，谢谢！

**Comment by SCY-X** [comment]
您好，能私发我一份解压密码吗，我绝对不会违背原作者意愿私自泄露，仅仅是自己学习之用, ftyixie@mail.scut.edu.cn，感激不尽~
